# Generated by Django 4.1.5 on 2023-02-01 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSetsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_created', models.DateField(auto_now_add=True, verbose_name='Created')),
                ('num_rows', models.PositiveIntegerField(verbose_name='Rows')),
            ],
        ),
        migrations.CreateModel(
            name='SchemaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_schema', models.CharField(max_length=45, verbose_name='Name schema')),
                ('column_separator', models.CharField(choices=[('coma', 'Coma'), ('pipe', 'Pipe'), ('semicolon', 'Semicolon'), ('tab', 'Tab')], default='coma', max_length=45, verbose_name='Column separator')),
                ('string_character', models.CharField(choices=[('double-quote', 'Double-quote'), ('quote', 'Quote')], default='double-quote', max_length=45, verbose_name='String character')),
                ('modified', models.DateTimeField(auto_now_add=True, verbose_name='modified')),
            ],
        ),
        migrations.CreateModel(
            name='ColumnModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(max_length=45, verbose_name='Column name')),
                ('column_type', models.CharField(choices=[('fullname', 'Full name'), ('age', 'Age'), ('phone', 'Phone'), ('email', 'E-mail'), ('address', 'Address')], max_length=45, verbose_name='Column type')),
                ('range_from', models.PositiveSmallIntegerField(default=18, verbose_name='From')),
                ('range_to', models.PositiveSmallIntegerField(default=60, verbose_name='To')),
                ('order', models.PositiveSmallIntegerField(verbose_name='Order')),
                ('schema', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fake_csv.schemamodel')),
            ],
        ),
    ]
