# Generated by Django 4.1.6 on 2023-03-05 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSetsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Created')),
                ('num_rows', models.PositiveIntegerField(verbose_name='Rows')),
            ],
        ),
        migrations.CreateModel(
            name='SchemaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='Name schema')),
                ('column_separator', models.CharField(choices=[('coma', 'Coma'), ('pipe', 'Pipe'), ('semicolon', 'Semicolon'), ('tab', 'Tab')], default='coma', max_length=45, verbose_name='Column separator')),
                ('string_character', models.CharField(choices=[('double-quote', 'Double-quote'), ('quote', 'Quote')], default='double-quote', max_length=45, verbose_name='String character')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
            ],
            options={
                'verbose_name': 'schema',
                'verbose_name_plural': 'schemas',
            },
        ),
        migrations.CreateModel(
            name='ColumnModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='Column name')),
                ('type', models.CharField(choices=[('fullname', 'Full name'), ('integer', 'Integer'), ('phone', 'Phone'), ('email', 'E-mail'), ('address', 'Address')], default='fullname', max_length=45, verbose_name='Column type')),
                ('range_from', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='From')),
                ('range_to', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='To')),
                ('order', models.PositiveSmallIntegerField(unique=True, verbose_name='Order')),
                ('schema', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fake_csv.schemamodel')),
            ],
            options={
                'verbose_name': 'column',
                'verbose_name_plural': 'columns',
            },
        ),
    ]
